### ISSUE TITLE
Segmentation fault on debian wheezy

### ISSUE THREAD

**Issue by DepreTux** [Cornu/dwmstatus#1]
Hi! When i run the compiled program it gives me a segmentation fault... Any ideas? Thanks!

**Comment by h2horn** [comment]
The program doesn't check if a file like "/sys/class/power_supply/BAT0/charge_now" exists. 
I didn't implement this, because on my computer all files exists...
Recently i got segmentation faults after resume, so checking isn't so bad :)
Something like 
if( access( fname, R_OK ) != -1 ) 
should do the trick
